GET http://localhost:8081/usuario/registar
Authorization: Bearer {{access_token}}
Accept: application/json

###
POST https://onesignal.com/api/v1/notifications
Content-Type: application/json
Authorization: Basic ODFlODdhMTUtMDAwNy00MTIxLTkwZTgtYTVlNDM0OGM3MTA0

{"app_id": "b856e4e5-e7c5-46cf-95e6-b67aea0fa4e7",
"contents": {"en": "English Octa"},
"headings": {"en": "JS Octaniel"},
"included_segments": ["Subscribed Users"]}

###


POST http://localhost:5000/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YW5ndWxhcjpAbmd1bEByMA==
bmobile: h

client=angular&username=chris@gmail.com&password=chris&grant_type=password

> {% client.global.set("access_token", response.body.access_token); %}
