GET http://localhost:8081/usuario/registar
Authorization: Bearer {{access_token}}
Accept: application/json

###
POST https://onesignal.com/api/v1/notifications
Content-Type: application/json; charset=utf-8
Authorization: Basic NmY1NTZkNjMtYmNlMy00ZDk3LTk3MTktMmNmODhlYWU5OGE0

{"app_id": "7cd8a33b-86f3-4167-8fe9-61d308cf3248",
"contents": {"en": "English Octa"},
"headings": {"en": "JS Octaniel"},
"included_segments": ["Subscribed Users"]}

###


POST http://localhost:5000/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic YW5ndWxhcjpAbmd1bEByMA==
bmobile: h

client=angular&username=chris@gmail.com&password=chris&grant_type=password

> {% client.global.set("access_token", response.body.access_token); %}
