name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: otaniel
          password: otanieljos
      - name: Build with Maven
        run: |
          mvn package
          docker build -t lpbp-api .
          docker tag lpbp-api otaniel/lpbp-api:0.1.0
          docker push otaniel/lpbp-api:0.1.0
      - name: ssh-pipeline
        uses: cross-the-world/ssh-pipeline@v1.2.0
        with:
          host: ${{ secrets.CLOUD_HOST }}
          user: ${{ secrets.CLOUD_USER }}
          pass: '${{ secrets.CLOUD_PASS }}'
          script: |
            echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker stop lpbp-backend
            echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker rm lpbp-backend
            echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker rmi $(echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker images otaniel/lpbp-api:0.1.0 -a -q) -f
            echo '${{ secrets.CLOUD_PASS }}'|sudo -S docker run --name lpbp-backend -d -p 8082:8080 otaniel/lpbp-api:0.1.0 --restart

